/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bhathigui.test;

import com.bhathigui.components.EasyTree;

/**
 *
 * @author Bhathi
 */
public class GUITest extends javax.swing.JFrame {

    /**
     * Creates new form GUITest
     */
    public GUITest() {
        initComponents();
        easyTree1.add("Gello", EasyTree.ROUND_BLUE)
                .child("Gello child", EasyTree.ROUND_BLUE)
                .sibling("Hello(sibling of gello child) ", EasyTree.ROUND_BLUE);
        sysLogPane1.addToSystemLog(new NullPointerException("Null pointer"));
        sysLogPane1.addToSystemLog("Hello");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        repeatPanel1 = new com.bhathigui.components.RepeatPanel();
        sysLogPane1 = new com.bhathigui.components.SysLogPane();
        clickButton1 = new com.bhathigui.components.ClickButton();
        clickDotButton1 = new com.bhathigui.components.ClickDotButton();
        clickLabel1 = new com.bhathigui.components.ClickLabel();
        fileTree1 = new com.bhathigui.components.FileTree();
        rSyntaxEmbedComponent1 = new com.bhathigui.components.RSyntaxEmbedComponent();
        repeatLabel1 = new com.bhathigui.components.RepeatLabel();
        repeatPanel2 = new com.bhathigui.components.RepeatPanel();
        clickButton2 = new com.bhathigui.components.ClickButton();
        whiteLabel1 = new com.bhathigui.components.WhiteLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        easyTree1 = new com.bhathigui.components.EasyTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clickButton1.setText("clickButton1");

        clickDotButton1.setText("clickDotButton1");

        clickLabel1.setText("clickLabel1");

        repeatLabel1.setText("repeatLabel1");
        repeatLabel1.setUrl("/com/bhathigui/res/back-box.png");

        repeatPanel2.setMouseEnterBorder(true);
        repeatPanel2.setUrl("/com/bhathigui/res/back-box.png");

        clickButton2.setText("clickButton2");

        javax.swing.GroupLayout repeatPanel2Layout = new javax.swing.GroupLayout(repeatPanel2);
        repeatPanel2.setLayout(repeatPanel2Layout);
        repeatPanel2Layout.setHorizontalGroup(
            repeatPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repeatPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clickButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        repeatPanel2Layout.setVerticalGroup(
            repeatPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(repeatPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(clickButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        whiteLabel1.setText("whiteLabel1");

        jScrollPane1.setViewportView(easyTree1);

        javax.swing.GroupLayout repeatPanel1Layout = new javax.swing.GroupLayout(repeatPanel1);
        repeatPanel1.setLayout(repeatPanel1Layout);
        repeatPanel1Layout.setHorizontalGroup(
            repeatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sysLogPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(repeatPanel1Layout.createSequentialGroup()
                .addGroup(repeatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(repeatPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(repeatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clickDotButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clickButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clickLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(repeatPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(repeatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(repeatPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeatLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(repeatPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(whiteLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(repeatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSyntaxEmbedComponent1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileTree1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        repeatPanel1Layout.setVerticalGroup(
            repeatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, repeatPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(repeatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(repeatPanel1Layout.createSequentialGroup()
                        .addComponent(fileTree1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(repeatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSyntaxEmbedComponent1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repeatPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(repeatPanel1Layout.createSequentialGroup()
                        .addComponent(clickButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(repeatPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(repeatPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clickDotButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clickLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(repeatLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(whiteLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(repeatPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sysLogPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(repeatPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(repeatPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.bhathigui.components.ClickButton clickButton1;
    private com.bhathigui.components.ClickButton clickButton2;
    private com.bhathigui.components.ClickDotButton clickDotButton1;
    private com.bhathigui.components.ClickLabel clickLabel1;
    private com.bhathigui.components.EasyTree easyTree1;
    private com.bhathigui.components.FileTree fileTree1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.bhathigui.components.RSyntaxEmbedComponent rSyntaxEmbedComponent1;
    private com.bhathigui.components.RepeatLabel repeatLabel1;
    private com.bhathigui.components.RepeatPanel repeatPanel1;
    private com.bhathigui.components.RepeatPanel repeatPanel2;
    private com.bhathigui.components.SysLogPane sysLogPane1;
    private com.bhathigui.components.WhiteLabel whiteLabel1;
    // End of variables declaration//GEN-END:variables
}
